# help:  ## Show help
#   @grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Clean autogenerated files
	@set -e -x; \
	echo "Removing dist..."; \
	rm -rf dist; \
	echo "Finding and deleting .DS_Store files..."; \
	find . -type f -name "*.DS_Store" -delete; \
	echo "Cleaning __pycache__, .pyc, and .pyo files..."; \
	find . -type d -name "__pycache__" -exec rm -rf {} +; \
	find . -type f -name "*.pyc" -delete; \
	find . -type f -name "*.pyo" -delete; \
	echo "Cleaning .pytest_cache directories..."; \
	find . -type d -name ".pytest_cache" -exec rm -rf {} +; \
	echo "Cleaning .ipynb_checkpoints directories..."; \
	find . -type d -name ".ipynb_checkpoints" -exec rm -rf {} +; \
	echo "Removing .coverage file..."; \
	rm -f .coverage; \
	echo "Cleaning doc/build/ directory..."; \
	rm -rf doc/build/
	# rm -rf /home/sayem/Desktop/deepHSI/temp_data

clean-logs: ## Clean logs
	@rm -rf logs/**
	@rm -rf notebooks/lightning_logs/**
	

format: ## Run pre-commit hooks
	@pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	@git pull origin main

test: ## Run not slow tests
	@pytest -k "not slow"

test-full: ## Run all tests
	@pytest

train: ## Train the model
	@python src/train.py
