# # In model.yaml
# defaults:
#   - _self_
#   - net: net_a  # Default network architecture

# You can add other model-related configurations here if needed
_target_: deepHSI.models.HSIClassificationModule

net: null

  # _target_: deepHSI.models.architectures.HSIFCModel
  # input_channels: 200
  # patch_size: 5
  # dropout: true
  # n_classes: 17

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

scheduler: null

num_classes: 17

custom_metrics:
  precision:
    _target_: torchmetrics.Precision
    num_classes: 17
    average: 'macro'
    task: 'multiclass'
  recall:
    _target_: torchmetrics.Recall
    num_classes: 17
    average: 'macro'
    task: 'multiclass'
  f1:
    _target_: torchmetrics.F1Score
    num_classes: 17
    average: 'macro'
    task: 'multiclass'

# # compile model for faster training with pytorch 2.0
# compile: false


