# https://wandb.ai

wandb:
  _target_: lightning.pytorch.loggers.WandbLogger
  # name: "Run-Resnet"  # Custom run name with a meaningful trailing name
  # project: "IndianPines"  # Your project name
  # save_dir: "/home/sayem/Desktop/deepHSI/notebooks/wandb"  # Directory to save logs
  offline: False  # Set to True if you want to run offline and upload later
  id: null  # Can set a specific ID for the run, useful for resuming
  anonymous: False  # Set to True to anonymously log data
  log_model: "all"  # Log all checkpoints during training
  # prefix: ""  # Prefix for all logged metrics, keep as empty string if not needed
  # tags:
  #   - "Baseline"
  #   - "HSI"  # Tags for the run
  # group: ""  # Group under which to organize the run, keep as empty string if not needed
  # job_type: ""  # Job type, keep as empty string if not needed
  # # config:
  # #   batch_size: ${hyperparams.batch_size, 64}  # Dynamically set from your hyperparams variable
