# # Same as `code-quality-pr.yaml` but triggered on commit to main branch
# # and runs on all files (instead of only the changed ones)

# name: Code Quality Main

# on:
#   push:
#     branches: [main]

# jobs:
#   code-quality:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Set up Python
#         uses: actions/setup-python@v2

#       - name: Run pre-commits
#         uses: pre-commit/action@v2.0.3


name: Code Quality Main

on:
  push:
    branches: [main]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit  # Ensure pre-commit is installed, adjust according to your project's needs

      - name: Run pre-commits on all files
        uses: pre-commit/action@v2.0.3
        with:
          extra_args: --all-files  # This ensures pre-commit checks run on all files, not just the changed ones
